POST http://localhost:3001/api/users/makeadmin
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBtYXJra29senp6QGhraS5maSIsImZpcnN0bmFtZSI6IlBldHRlcmkiLCJsYXN0bmFtZSI6Ik1hcmtrb2xhIiwiYWRtaW4iOmZhbHNlLCJpZCI6IjVhZWI2ZTc5YWIxOTg5MWI3ODBmNmU4MiIsImlhdCI6MTUyNTM3ODY5MX0.k16rHi_eXt0BuQmJrdWyk6XRbd3qxzfF3SQKJlbwPtg

{
  "userId": "5aeb6e50ab19891b780f6e81"
}