POST http://localhost:3001/api/observations
content-type: application/json

{
  "latitude": 54.039991,
  "longitude": 15.3822811,
  "date": "04-05-2018",
  "additionalComments": "Vautsi vau!",
  "userId": "5aeaded6d21d9f263c60c4aa",
  "speciesId": "5aeaef6f6eedee1b58e74b26"
}