POST http://localhost:3001/api/users
content-type: application/json

{
  "firstname": "Petteri",
  "lastname": "Markkola",
  "email": "pete@malmi.fi",
  "address": "Pasteurinkatu 1",
  "zipcode": "00790",
  "town": "Helsinki",
  "phone": "04238911",
  "password": "Perkeles6!"
}